# ======================================================================
# Configuration file for robotic insertion log plotter
# ======================================================================
# Adjust these parameters according to your data and preferences
#
# Directory paths can be:
# - Relative to script location (e.g., "../data")
# - Absolute paths (e.g., "/home/user/data")
# - Command line arguments override these settings

# ======================================================================
# DIRECTORY CONFIGURATION
# ======================================================================
directories:
  data_dir: "../data"           # Directory containing CSV data files
  results_dir: "../results"     # Directory containing YAML result files  
  plots_dir: "../plots"         # Directory where plots will be saved

# ======================================================================
# DATA PROCESSING CONFIGURATION
# ======================================================================
data:
  default_sampling_freq: 100.0  # Hz - sampling frequency for time axis reconstruction

# ======================================================================
# PLOTTING CONFIGURATION
# ======================================================================
plotting:
  # General plot settings
  figure_size: [12, 6]          # [width, height] in inches
  line_width: 1.0               # Default line width
  grid_alpha: 0.3               # Grid transparency
  dpi: 100                      # Plot resolution
  
  # Color scheme
  colors:
    pose: 'blue'                # Color for pose data
    force: 'red'                # Color for force data
    trajectory: 'viridis'       # Colormap for 3D trajectories
  
  # 3D trajectory plot settings
  trajectory:
    point_size: 2               # Size of trajectory points
    alpha: 0.7                  # Transparency of trajectory points
    limit_files: false          # Limit to first 5 files for trajectory plots
  
  # Pose-force plot settings (multi-trial support)
  pose_force:
    alignment: 'time'           # 'time' or 'distance' - how to align multiple trials
    show_individual_trials: true # Show faded individual trial lines
    interpolation_points: 1000  # Number of points for interpolation grid
    std_dev_bands: true         # Show standard deviation bands
    individual_alpha: 0.3       # Transparency for individual trial lines
    max_duration: 7.0          # Maximum duration in seconds to plot

# ======================================================================
# FILE HANDLING CONFIGURATION
# ======================================================================
files:
  auto_save_plots: true         # Automatically save plots to files
  plot_format: 'png'            # Output format: 'png', 'pdf', 'svg'
  timestamp_plots: true         # Add timestamp to plot filenames

# ======================================================================
# ANALYSIS CONFIGURATION
# ======================================================================
analysis:
  # Keywords that indicate success in YAML result files
  success_keywords: ['success', 'completed', 'finished']
  
  # Keywords for time values in YAML result files
  time_keywords: ['required_time', 'duration', 'time', 'trial_duration']
